repos:
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

-   repo: https://github.com/ejba/pre-commit-maven
    rev: v0.2.0
    hooks:
    -   id: maven-spotless-apply
